#!/usr/bin/env bash

set -e

spec=$1

cwd="$(cd "$(dirname "$0")" && pwd)"

if [ -z "$spec" ]
then
    echo "Usage: fly-cypress SPEC"
    echo
    echo "e.g. fly-cypress cypress/integration/publishers.spec.ts"
    exit 1
fi

SPEC=$spec fly --target ci \
    execute \
    --config "$cwd/pipeline/tasks/cypress.yml" \
    --input source="$cwd" \
    --output test-results=test-results \
    --output metrics=metrics
