#!/usr/bin/env bash

set -e

spec=$1

cwd="$(cd "$(dirname "$0")" && pwd)"

if [ -z "$spec" ]
then
    echo "Usage: fly-jest SPEC"
    echo
    echo "e.g. fly-jest api/*"
    exit 1
fi

SPEC=$spec fly --target ci \
    execute \
    --config "$cwd/pipeline/tasks/jest.yaml" \
    --input source="$cwd" \
    --output metrics=metrics
