---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/browsers
    tag: 'node16.13.2-chrome100-ff98'

inputs:
- name: source

outputs:
- name: test-results
- name: metrics

run:
  path: source/pipeline/scripts/cypress

params:
  SPEC:
  DESCRIPTION:
  CYPRESS_PUBLISHER_USERNAME:
  CYPRESS_PUBLISHER_PASSWORD:

caches:
- path: ../../../root/.cache
- path: ../../../root/.npm
