---
meta:
  upload_media:
    &upload_media
    put: test-results
    params:
      file: test-results/results.tar
      predefined_acl: projectPrivate

  upload_metrics:
    &upload_metrics
    put: replace-me
    params:
      file: metrics/prometheus
      cache_control: "private, max-age=0, no-transform"
      predefined_acl: "publicRead"

jobs:
- name: p1-tests
  plan:
  - get: source
    resource: smoke-tests
  - get: not-often
    trigger: true
  - in_parallel:
    - task: run-ui-tests
      file: source/pipeline/tasks/cypress.yaml
      params:
        SPEC: cypress/integration/p1.legacy-publishers.spec.ts
      on_failure: *upload_media
      ensure:
        <<: *upload_metrics
        put: p1-ui-metrics
    - task: run-bo-web-app-ui-tests
      file: source/pipeline/tasks/cypress.yaml
      params:
        SPEC: cypress/integration/p1.bo-web-app.spec.ts
        CYPRESS_PUBLISHER_USERNAME: ((publisher.username))
        CYPRESS_PUBLISHER_PASSWORD: ((publisher.password))
      on_failure: *upload_media
      ensure:
        <<: *upload_metrics
        put: p1-ui-metrics
    - task: run-api-tests
      file: source/pipeline/tasks/jest.yaml
      timeout: 0h2m
      params:
        SPEC: ./api/p1.spec.ts
        TEACHERS_USERNAME: ((smoke-tests-teachers.username))
        TEACHERS_PASSWORD: ((smoke-tests-teachers.password))
      ensure:
        <<: *upload_metrics
        put: p1-api-metrics

- name: p2-tests
  plan:
  - get: source
    resource: smoke-tests
  - get: not-often
    trigger: true
  - task: run
    file: source/pipeline/tasks/jest.yaml
    params:
      SPEC: ./api/p2.spec.ts
      TEACHERS_USERNAME: ((smoke-tests-teachers.username))
      TEACHERS_PASSWORD: ((smoke-tests-teachers.password))
    ensure:
      <<: *upload_metrics
      put: p2-api-metrics

resources:
- name: smoke-tests
  type: git
  icon: fire
  source:
    branch: master
    uri: https://github.com/boclips/smoke-tests.git

- name: test-results
  type: gcs
  icon: video
  source:
    bucket: boclips-test-results
    versioned_file: "smoke-tests/results.tar"

- name: p1-ui-metrics
  type: gcs
  icon: chart-line
  source:
    bucket: boclips-smoke-test-metrics
    versioned_file: p1-ui-metrics

- name: p1-api-metrics
  type: gcs
  icon: chart-line
  source:
    bucket: boclips-smoke-test-metrics
    versioned_file: p1-api-metrics

- name: p2-api-metrics
  type: gcs
  icon: chart-line
  source:
    bucket: boclips-smoke-test-metrics
    versioned_file: p2-api-metrics

- name: not-often
  type: time
  icon: clock-outline
  source:
    interval: 10m

resource_types:
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource
    tag: "v0.5.1"
