#!/usr/bin/env bash

produce_metric () {
    gauge_value=$1
    spec_name=$(basename -- "$2")
    priority=$(basename -- "$2" | cut -c 1-2 | tr a-z A-Z)
    description=$3
    gauge_name=boclips_smoke_test_failure_total
    cat <<EOF
# HELP $gauge_name
# TYPE $gauge_name gauge
$gauge_name{spec="$spec_name",priority="$priority",description="$description"} $gauge_value.0
EOF
}

if [ -z "$SPEC" ]
then
    echo "Must specify SPEC"
    exit 1
fi

if [ -z "$DESCRIPTION" ]
then
    echo "Must specify DESCRIPTION"
    exit 1
fi

metrics_output=../../metrics/prometheus
cwd="$(cd "$(dirname "$0")" && pwd)"

(
cd source || exit 1
cd api || exit 1
npm ci || exit 1

retries=3
"$cwd/run-with-retries" $SPEC $retries

if [[ $? -ne 0 ]]
then
  produce_metric 1 "$SPEC" "$DESCRIPTION" > $metrics_output
  exit 1
else
  produce_metric 0 "$SPEC" "$DESCRIPTION" > $metrics_output
  exit 0
fi
)
